query PullRequestsOpen ($repo_owner: String!, $repo_name: String!, $after: String) {
  repository(owner: $repo_owner, name: $repo_name) {
    pullRequests(first: 100, after: $after, states:OPEN) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        number
        updatedAt
        createdAt
        assignees(first: 10) {
          nodes {
            login
            databaseId
          }
        }
        labels(first:5, orderBy:{field:NAME, direction:DESC}) {
          nodes {
            name
          }
        }
      }
    }
  }
}
